<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenusTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menus')->delete();
        
        \DB::table('menus')->insert(array (
            0 => 
            array (
                'id' => 1,
                'parent_id' => NULL,
                'name' => 'Dashboard',
                'bn_name' => 'ড্যাশবোর্ড',
                'system_name' => 'Dashboard',
                'route_name' => 'dashboard',
                'icon' => 'uil-home-alt',
                'order_by' => 6,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-03-19 14:04:30',
                'updated_at' => '2024-01-10 06:02:06',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'parent_id' => NULL,
                'name' => 'User Management',
                'bn_name' => 'ইউজার ম্যানেজমেন্ট',
                'system_name' => 'User Management',
                'route_name' => NULL,
                'icon' => NULL,
                'order_by' => 8,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-03-19 18:06:39',
                'updated_at' => '2024-01-10 06:02:06',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'parent_id' => 2,
                'name' => 'User',
                'bn_name' => 'ইউজার',
                'system_name' => 'User',
                'route_name' => 'user.index',
                'icon' => NULL,
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-03-19 18:08:09',
                'updated_at' => '2023-03-31 18:10:57',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 5,
                'parent_id' => 2,
                'name' => 'Role',
                'bn_name' => 'রোল',
                'system_name' => 'Role',
                'route_name' => 'role.index',
                'icon' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-03-19 18:17:21',
                'updated_at' => '2023-03-31 18:11:32',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 25,
                'parent_id' => NULL,
                'name' => 'Menu Management',
                'bn_name' => 'মেন্যু ম্যানেজমেন্ট',
                'system_name' => 'Menu Management',
                'route_name' => '',
                'icon' => NULL,
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-04-03 10:38:48',
                'updated_at' => '2024-01-10 06:02:06',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 26,
                'parent_id' => 25,
                'name' => 'Menu',
                'bn_name' => 'মেন্যু',
                'system_name' => 'Menu',
                'route_name' => 'menu.index',
                'icon' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-04-03 10:39:32',
                'updated_at' => '2023-04-03 10:39:32',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 27,
                'parent_id' => NULL,
                'name' => 'About Institute',
                'bn_name' => 'প্রতিষ্ঠান সম্পর্কে',
                'system_name' => 'About Institute',
                'route_name' => NULL,
                'icon' => NULL,
                'order_by' => 13,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-11 13:35:23',
                'updated_at' => '2024-01-10 06:02:06',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 28,
                'parent_id' => 27,
                'name' => 'Pages',
                'bn_name' => 'পেইজ',
                'system_name' => 'Pages',
                'route_name' => 'pages.index',
                'icon' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-11 13:35:49',
                'updated_at' => '2023-06-11 13:36:35',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 29,
                'parent_id' => NULL,
                'name' => 'Administrator Info.',
                'bn_name' => 'প্রশাসনিক তথ্য',
                'system_name' => 'Administrator Info.',
                'route_name' => NULL,
                'icon' => NULL,
                'order_by' => 22,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-11 13:37:43',
                'updated_at' => '2024-01-10 06:02:06',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 30,
                'parent_id' => 29,
                'name' => 'Principal/Vice Principal Message',
                'bn_name' => 'অধ্যক্ষ/উপাধ্যক্ষ বার্তা',
                'system_name' => 'Principle',
                'route_name' => 'principle.index',
                'icon' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-11 13:38:49',
                'updated_at' => '2024-01-21 05:02:31',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 31,
                'parent_id' => NULL,
                'name' => 'Gallery',
                'bn_name' => 'গ্যালারি',
                'system_name' => 'Gallery',
                'route_name' => NULL,
                'icon' => NULL,
                'order_by' => 40,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-11 13:54:20',
                'updated_at' => '2024-01-16 06:36:45',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 32,
                'parent_id' => 78,
                'name' => 'Photo Gallary',
                'bn_name' => 'ফটো গ্যালারি',
                'system_name' => 'Photo Gallary',
                'route_name' => 'photogallerys.index',
                'icon' => NULL,
                'order_by' => 4,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-11 13:54:53',
                'updated_at' => '2023-06-11 13:54:53',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 33,
                'parent_id' => 78,
                'name' => 'Video Gallary',
                'bn_name' => 'ভিডিও গ্যালারি',
                'system_name' => 'Video Gallary',
                'route_name' => 'videogallerys.index',
                'icon' => NULL,
                'order_by' => 3,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-11 13:55:31',
                'updated_at' => '2023-06-11 13:55:31',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 36,
                'parent_id' => NULL,
                'name' => 'Useful Link',
                'bn_name' => 'লিংক',
                'system_name' => 'Useful Link',
                'route_name' => NULL,
                'icon' => NULL,
                'order_by' => 37,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-11 14:09:21',
                'updated_at' => '2024-01-16 06:36:45',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 37,
                'parent_id' => 78,
                'name' => 'Link',
                'bn_name' => 'লিংক',
                'system_name' => 'Link',
                'route_name' => 'usefullink.index',
                'icon' => NULL,
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-11 14:09:57',
                'updated_at' => '2023-06-11 14:09:57',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 38,
                'parent_id' => 29,
                'name' => 'Add Members',
                'bn_name' => 'সদস্য যোগ করুন',
                'system_name' => 'Add Members',
                'route_name' => 'members.index',
                'icon' => NULL,
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-11 14:28:27',
                'updated_at' => '2024-01-21 05:02:19',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 39,
                'parent_id' => NULL,
                'name' => 'Academic Info.',
                'bn_name' => 'একাডেমিক তথ্যসমূহ',
                'system_name' => 'Academic Info.',
                'route_name' => NULL,
                'icon' => NULL,
                'order_by' => 14,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-13 13:34:38',
                'updated_at' => '2024-01-10 06:02:06',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 40,
                'parent_id' => 27,
                'name' => 'Academic Calender',
                'bn_name' => 'শিক্ষা বর্ষপঞ্জি',
                'system_name' => 'Academic Calender',
                'route_name' => 'academiccalender.index',
                'icon' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-13 13:35:34',
                'updated_at' => '2023-06-13 13:35:34',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 41,
                'parent_id' => 39,
                'name' => 'Class Routine',
                'bn_name' => 'ক্লাস রুটিন',
                'system_name' => 'Class Routine',
                'route_name' => 'classroutine.index',
                'icon' => NULL,
                'order_by' => 3,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-13 13:36:26',
                'updated_at' => '2024-01-08 05:16:27',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 42,
                'parent_id' => 27,
                'name' => 'Holiday List',
                'bn_name' => 'ছুটির দিন',
                'system_name' => 'Holiday List',
                'route_name' => 'holidaylist.index',
                'icon' => NULL,
                'order_by' => 3,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-13 13:38:27',
                'updated_at' => '2023-06-13 13:38:27',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 50,
                'parent_id' => 39,
                'name' => 'Admission Info.',
                'bn_name' => 'ভর্তি সংক্রান্ত তথ্য',
                'system_name' => 'Admission Info.',
                'route_name' => 'admissioninfo.index',
                'icon' => NULL,
                'order_by' => 10,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-13 14:24:49',
                'updated_at' => '2024-01-21 05:04:37',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 51,
                'parent_id' => NULL,
                'name' => 'Class Info.',
                'bn_name' => 'শ্রেণী সম্পর্কিত তথ্য',
                'system_name' => 'Class Info.',
                'route_name' => NULL,
                'icon' => NULL,
                'order_by' => 24,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-14 05:54:43',
                'updated_at' => '2024-01-10 06:02:06',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 54,
                'parent_id' => 51,
                'name' => 'Add Section',
                'bn_name' => 'সেকশন যোগ করুন',
                'system_name' => 'Add Section',
                'route_name' => 'addsection.index',
                'icon' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-14 05:56:11',
                'updated_at' => '2024-01-23 06:53:22',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 55,
                'parent_id' => NULL,
                'name' => 'Exam Info',
                'bn_name' => 'পরীক্ষা সংক্রান্ত তথ্য',
                'system_name' => 'Exam Info',
                'route_name' => 'examinfo',
                'icon' => NULL,
                'order_by' => 21,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-15 05:53:10',
                'updated_at' => '2024-01-10 06:02:06',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 56,
                'parent_id' => 55,
                'name' => 'Exam Routine',
                'bn_name' => 'পরীক্ষার রুটিন',
                'system_name' => 'Exam Routine',
                'route_name' => 'examroutine.index',
                'icon' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-15 05:54:02',
                'updated_at' => '2023-06-15 05:54:02',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 57,
                'parent_id' => 39,
                'name' => 'Syllabus',
                'bn_name' => 'সিলেবাস',
                'system_name' => 'Syllabus',
                'route_name' => 'syllabus.index',
                'icon' => NULL,
                'order_by' => 6,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-15 05:54:32',
                'updated_at' => '2024-01-08 11:22:17',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 58,
                'parent_id' => 55,
                'name' => 'Lesson Plan',
                'bn_name' => 'পাঠ পরিকল্পনা',
                'system_name' => 'Lesson Plan',
                'route_name' => 'lessonplan.index',
                'icon' => NULL,
                'order_by' => 3,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-15 05:54:59',
                'updated_at' => '2023-06-15 05:54:59',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 59,
                'parent_id' => 55,
                'name' => 'Suggestion',
                'bn_name' => 'সাজেশন্স',
                'system_name' => 'Suggestion',
                'route_name' => 'suggestion.index',
                'icon' => NULL,
                'order_by' => 4,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-15 05:55:51',
                'updated_at' => '2023-06-15 05:55:51',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 60,
                'parent_id' => NULL,
                'name' => 'Teacher & Staff info.',
                'bn_name' => 'শিক্ষক - কর্মচারীদের তথ্য',
                'system_name' => 'Teacher & Staff info.',
                'route_name' => NULL,
                'icon' => NULL,
                'order_by' => 28,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-15 06:30:54',
                'updated_at' => '2024-01-16 06:36:45',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 61,
                'parent_id' => 60,
                'name' => 'Department',
                'bn_name' => 'বিভাগ যুক্ত করুন',
                'system_name' => 'Department',
                'route_name' => 'department.index',
                'icon' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-15 06:31:38',
                'updated_at' => '2023-06-15 06:31:38',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 62,
                'parent_id' => 60,
                'name' => 'Teacher & Staff',
                'bn_name' => 'শিক্ষক - কর্মচারী যুক্ত করুন',
                'system_name' => 'Teacher & Staff',
                'route_name' => 'teacherstaff.index',
                'icon' => NULL,
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-15 06:32:10',
                'updated_at' => '2023-06-15 06:32:10',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 63,
                'parent_id' => 78,
                'name' => 'Website Setting',
                'bn_name' => 'সেটিংস',
                'system_name' => 'Website Setting',
                'route_name' => 'setting.create',
                'icon' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-18 05:29:49',
                'updated_at' => '2023-09-23 09:50:25',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 64,
                'parent_id' => NULL,
                'name' => 'Registration Info',
                'bn_name' => 'অ্যাডমিশন তথ্য',
                'system_name' => 'Admission Info',
                'route_name' => NULL,
                'icon' => NULL,
                'order_by' => 30,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-27 09:20:02',
                'updated_at' => '2024-01-16 06:36:45',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 65,
                'parent_id' => 64,
                'name' => 'View Admission Data',
                'bn_name' => 'অ্যাডমিশন তথ্য',
                'system_name' => 'View Admission Data',
                'route_name' => 'admission_info.index',
                'icon' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-06-27 09:20:55',
                'updated_at' => '2023-06-27 09:20:56',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 67,
                'parent_id' => 27,
                'name' => 'Teaching permission and recognition',
                'bn_name' => 'পাঠাদানের অনুমতি ও স্বীকৃতি',
                'system_name' => 'Teaching permission and recognition',
                'route_name' => 'teaching_permission.index',
                'icon' => NULL,
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-09-10 09:47:13',
                'updated_at' => '2023-09-10 09:47:14',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 68,
                'parent_id' => 27,
                'name' => 'MPO/Nationalization Info',
                'bn_name' => 'এমপিও/জাতীয়করণ তথ্য',
                'system_name' => 'MPO_Nationalization Info',
                'route_name' => 'mpo_nationalization.index',
                'icon' => NULL,
                'order_by' => 3,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-09-10 09:48:59',
                'updated_at' => '2023-09-10 09:48:59',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 78,
                'parent_id' => NULL,
                'name' => 'Project Settings',
                'bn_name' => 'প্রজেক্ট সেটিংস',
                'system_name' => 'Project Settings',
                'route_name' => NULL,
                'icon' => NULL,
                'order_by' => 34,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-09-23 09:50:25',
                'updated_at' => '2024-01-16 06:36:45',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 80,
                'parent_id' => 78,
                'name' => 'Backup',
                'bn_name' => 'ব্যাকআপ',
                'system_name' => 'Backup',
                'route_name' => 'backup.index',
                'icon' => NULL,
                'order_by' => 5,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-09-23 09:56:24',
                'updated_at' => '2023-09-23 09:56:24',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 81,
                'parent_id' => 29,
                'name' => 'Notices',
                'bn_name' => 'নোটিশ',
                'system_name' => 'Notices',
                'route_name' => 'notices.index',
                'icon' => NULL,
                'order_by' => 5,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-10-04 05:33:50',
                'updated_at' => '2024-01-21 05:00:21',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 84,
                'parent_id' => 39,
                'name' => 'Shop Information',
                'bn_name' => 'ল্যাব/ সপ',
                'system_name' => 'Shop Information',
                'route_name' => 'shop_info.index',
                'icon' => NULL,
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-12-31 06:21:09',
                'updated_at' => '2024-01-08 05:16:44',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 85,
                'parent_id' => 51,
                'name' => 'Semester',
                'bn_name' => 'সেমিস্টার',
                'system_name' => 'Semester',
                'route_name' => 'semester.index',
                'icon' => NULL,
                'order_by' => 4,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-12-31 06:44:44',
                'updated_at' => '2023-12-31 06:44:44',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 86,
                'parent_id' => 39,
                'name' => 'About Department',
                'bn_name' => 'ডিপার্টমেন্ট সম্পর্কে',
                'system_name' => 'About Department',
                'route_name' => 'about_department.index',
                'icon' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2023-12-31 11:19:14',
                'updated_at' => '2023-12-31 11:19:48',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 87,
                'parent_id' => 39,
                'name' => 'Online Class Routine',
                'bn_name' => 'অনলাইন ক্লাস রুটিন',
                'system_name' => 'Online Class Routine',
                'route_name' => 'onlineclassroutine.index',
                'icon' => NULL,
                'order_by' => 4,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2024-01-08 07:22:53',
                'updated_at' => '2024-01-08 07:28:10',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 88,
                'parent_id' => 39,
                'name' => 'Digital Class Content',
                'bn_name' => 'ডিজিটাল ক্লাস কন্টেন্ট',
                'system_name' => 'Digital Class Content',
                'route_name' => 'digitalclasscontent.index',
                'icon' => NULL,
                'order_by' => 5,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2024-01-08 10:32:31',
                'updated_at' => '2024-01-08 10:32:55',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 89,
                'parent_id' => 39,
                'name' => 'Semester Plan',
                'bn_name' => 'সেমিস্টার প্ল্যান',
                'system_name' => 'Semester Plan',
                'route_name' => 'semesterplan.index',
                'icon' => NULL,
                'order_by' => 7,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2024-01-08 11:51:24',
                'updated_at' => '2024-01-08 17:33:46',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 90,
                'parent_id' => 39,
                'name' => 'Student Project',
                'bn_name' => 'শিক্ষাথীদের প্রোজেক্টসমূহ',
                'system_name' => 'Student Project',
                'route_name' => 'studentproject.index',
                'icon' => NULL,
                'order_by' => 8,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2024-01-08 18:58:19',
                'updated_at' => '2024-01-08 18:58:19',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 91,
                'parent_id' => 39,
                'name' => 'Probidhan',
                'bn_name' => 'প্রবিধান',
                'system_name' => 'Probidhan',
                'route_name' => 'probidhan.index',
                'icon' => NULL,
                'order_by' => 9,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2024-01-09 05:15:20',
                'updated_at' => '2024-01-09 05:15:20',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 92,
                'parent_id' => NULL,
                'name' => 'Result Infos',
                'bn_name' => 'রেজাল্ট সংক্রান্ত তথ্য',
                'system_name' => 'Result Infos',
                'route_name' => NULL,
                'icon' => NULL,
                'order_by' => 15,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2024-01-09 06:15:30',
                'updated_at' => '2024-01-10 06:02:06',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 93,
                'parent_id' => 92,
                'name' => 'Internal Exam',
                'bn_name' => 'অভ্যন্তরীণ পরীক্ষা',
                'system_name' => 'Internal Exam Result',
                'route_name' => 'internal_result.index',
                'icon' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2024-01-09 06:16:31',
                'updated_at' => '2024-01-09 07:32:04',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 94,
                'parent_id' => 92,
                'name' => 'Board Final Exam',
                'bn_name' => 'বোর্ড ফাইনাল পরীক্ষা',
                'system_name' => 'Board Final Exam',
                'route_name' => 'board_result.index',
                'icon' => NULL,
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2024-01-09 07:31:03',
                'updated_at' => '2024-01-09 07:31:03',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 95,
                'parent_id' => NULL,
                'name' => 'Job Placement',
                'bn_name' => 'জব প্লেসমেন্ট',
                'system_name' => 'Job Placement',
                'route_name' => NULL,
                'icon' => NULL,
                'order_by' => 16,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2024-01-09 10:56:51',
                'updated_at' => '2024-01-10 06:02:06',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 96,
                'parent_id' => 95,
                'name' => 'Employment Information',
                'bn_name' => 'কর্মসংস্থান সংক্রান্ত তথ্যাবলী',
                'system_name' => 'Employment Information',
                'route_name' => 'employment_information.index',
                'icon' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2024-01-09 10:58:31',
                'updated_at' => '2024-01-09 10:58:31',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 97,
                'parent_id' => 95,
                'name' => 'Recruitment Notices',
                'bn_name' => 'নিয়োগ বিজ্ঞপ্তিসমূহ',
                'system_name' => 'Recruitment Notices',
                'route_name' => 'recruitment_notices.index',
                'icon' => NULL,
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2024-01-09 11:52:50',
                'updated_at' => '2024-01-09 11:52:50',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 98,
                'parent_id' => 95,
                'name' => 'Old Students Success',
                'bn_name' => 'পুরাতন শিক্ষাথীদের সাফল্য',
                'system_name' => 'Old Student Success',
                'route_name' => 'old_student_success.index',
                'icon' => NULL,
                'order_by' => 3,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2024-01-10 05:10:13',
                'updated_at' => '2024-01-10 05:10:13',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 99,
                'parent_id' => NULL,
                'name' => 'Industries Links',
                'bn_name' => 'ইন্ডাস্ট্রি লিংকেজ',
                'system_name' => 'Industries Links',
                'route_name' => NULL,
                'icon' => NULL,
                'order_by' => 17,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2024-01-10 05:56:49',
                'updated_at' => '2024-01-10 06:02:06',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 102,
                'parent_id' => 99,
                'name' => 'Industries Links Menus',
                'bn_name' => 'ইন্ডাস্ট্রি লিংকেজ মেন্যু সমূহ',
                'system_name' => 'Industries Links Menus',
                'route_name' => 'industry_linkages.index',
                'icon' => NULL,
                'order_by' => 3,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2024-01-11 05:02:59',
                'updated_at' => '2024-01-11 05:02:59',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 103,
                'parent_id' => 95,
                'name' => 'Working Alumni Database',
                'bn_name' => 'কর্মরত প্রাক্তন ছাত্র-ছাত্রীদের ডাটাবেজ',
                'system_name' => 'Working Alumni Database',
                'route_name' => 'jobplacement.index',
                'icon' => NULL,
                'order_by' => 4,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2024-01-13 10:08:47',
                'updated_at' => '2024-01-13 10:08:47',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 104,
                'parent_id' => 95,
                'name' => 'Attachment Of CV Of Job Aspirants',
                'bn_name' => 'কর্ম প্রত্যাশীদের বায়োডাটা সংযুক্তকরণ',
                'system_name' => 'Attachment Of CV Of Job Aspirants',
                'route_name' => 'cvattached.index',
                'icon' => NULL,
                'order_by' => 5,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2024-01-14 07:02:21',
                'updated_at' => '2024-01-14 07:02:21',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 105,
                'parent_id' => NULL,
                'name' => 'Subject Info',
                'bn_name' => 'বিষয় সম্পর্কিত তথ্য',
                'system_name' => 'Subject Info',
                'route_name' => NULL,
                'icon' => NULL,
                'order_by' => 25,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2024-01-16 06:36:45',
                'updated_at' => '2024-01-16 06:36:45',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 106,
                'parent_id' => 105,
                'name' => 'Add Subject',
                'bn_name' => 'বিষয় যোগ করুন',
                'system_name' => 'Add Subject',
                'route_name' => 'add_subject.index',
                'icon' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2024-01-16 06:38:45',
                'updated_at' => '2024-01-16 06:38:45',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 107,
                'parent_id' => 105,
                'name' => 'Subject Priority',
                'bn_name' => 'বিষয় অগ্রাধিকার',
                'system_name' => 'Subject Priority',
                'route_name' => 'subjectpriority.index',
                'icon' => NULL,
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2024-01-18 06:34:33',
                'updated_at' => '2024-01-18 07:11:02',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 108,
                'parent_id' => 29,
                'name' => 'Focul Point',
                'bn_name' => 'ফোকাল পয়েন্ট',
                'system_name' => 'Focul Point',
                'route_name' => 'focul_point.index',
                'icon' => NULL,
                'order_by' => 3,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2024-01-21 05:00:21',
                'updated_at' => '2024-01-21 05:05:04',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 109,
                'parent_id' => 39,
            'name' => 'National Integrity Strategy (NIS)',
            'bn_name' => 'শুদ্ধাচার সংক্রান্ত তথ্য (NIS)',
            'system_name' => 'National Integrity Strategy (NIS)',
                'route_name' => 'nis_info.index',
                'icon' => NULL,
                'order_by' => 11,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2024-01-23 05:09:48',
                'updated_at' => '2024-01-23 05:09:48',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}